CREATE TABLE correntista (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(200) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    dataNascimento DATE NOT NULL,
    CONSTRAINT id_correntista_pk PRIMARY KEY (id)
 );

INSERT INTO correntista (nome, cpf, dataNascimento) VALUES ('Badeco da Silva', '54482203041', '1992-01-12');
INSERT INTO correntista (nome, cpf, dataNascimento) VALUES ('Marcela Barcelos', '58786738003', '1997-03-23');
INSERT INTO correntista (nome, cpf, dataNascimento) VALUES ('Estevão Cordova', '60904959058', '1989-07-02');


