CREATE TABLE contaCorrente (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_correntista int,
    id_agencia int,
    limite DECIMAL(18,2),
    saldo DECIMAL(18,2),
    ativo char(1),
    CONSTRAINT id_contaCorrente_pk PRIMARY KEY (id)
 );

 ALTER TABLE IF EXISTS contaCorrente ADD CONSTRAINT id_correntista_fk FOREIGN KEY (id_correntista) references correntista;
 ALTER TABLE IF EXISTS contaCorrente ADD CONSTRAINT id_agencia_fk FOREIGN KEY (id_agencia) references agencia;

INSERT INTO contaCorrente (id_correntista, id_agencia, limite, saldo, ativo) VALUES (1, 2, 1000.00, 0.00, 'F');
INSERT INTO contaCorrente (id_correntista, id_agencia, limite, saldo, ativo) VALUES (2, 1, 15000.00, 4381.74, 'T');
INSERT INTO contaCorrente (id_correntista, id_agencia, limite, saldo, ativo) VALUES (3, 3, 200000.00, 142893.89, 'T');
