CREATE TABLE conta_corrente (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_correntista int,
    id_agencia int,
    id_tipo_conta int,
    limite DECIMAL(18,2),
    saldo DECIMAL(18,2),
    ativa char(1),
    CONSTRAINT id_contaCorrente_pk PRIMARY KEY (id)
 );

ALTER TABLE IF EXISTS conta_corrente ADD CONSTRAINT id_correntista_fk FOREIGN KEY (id_correntista) references correntista;
ALTER TABLE IF EXISTS conta_corrente ADD CONSTRAINT id_agencia_fk FOREIGN KEY (id_agencia) references agencia;
ALTER TABLE IF EXISTS conta_corrente ADD CONSTRAINT id_tipo_conta_fk FOREIGN KEY (id_tipo_conta) references tipo_conta;

